import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import type { Workflow, WorkflowOutput } from "@memory-middleware/shared-types";
import { useAuth } from "../context/AuthContext.js";
import {
  fetchWorkflow,
  fetchWorkflowRunDetail,
  fetchWorkflowRuns,
} from "../lib/domain-engine-api.js";
import { WorkflowSubNav } from "../components/domain-engine/WorkflowSubNav.js";
import { Badge } from "../components/ui/Badge.js";
import { Button } from "../components/ui/Button.js";
import { PageHeader } from "../components/ui/PageHeader.js";
import { Panel } from "../components/ui/Panel.js";
import { TextField } from "../components/ui/TextField.js";

interface OutputRow extends WorkflowOutput {
  runStartedAt: string;
}

export function WorkflowOutputsPage() {
  const { workflowId } = useParams();
  const { workspace } = useAuth();
  const workspaceId = workspace?.workspaceId ?? "";
  const [workflow, setWorkflow] = useState<Workflow | null>(null);
  const [outputs, setOutputs] = useState<OutputRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("");
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const load = useCallback(async () => {
    if (!workspaceId || !workflowId) return;
    setLoading(true);
    setError(null);
    try {
      const wf = await fetchWorkflow(workspaceId, workflowId);
      setWorkflow(wf);
      const runs = await fetchWorkflowRuns(workspaceId, workflowId, 50);
      const runsWithOutputs = runs.filter((run) => run.outputCount > 0);
      const details = await Promise.all(
        runsWithOutputs.map((run) => fetchWorkflowRunDetail(workspaceId, run.workflowRunId)),
      );
      const rows: OutputRow[] = [];
      for (const detail of details) {
        for (const output of detail.outputs) {
          rows.push({ ...output, runStartedAt: detail.startedAt });
        }
      }
      rows.sort(
        (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
      );
      setOutputs(rows);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load outputs");
    } finally {
      setLoading(false);
    }
  }, [workspaceId, workflowId]);

  useEffect(() => {
    void load();
  }, [load]);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    const type = typeFilter.trim().toLowerCase();
    return outputs.filter((output) => {
      if (type && output.outputType.toLowerCase() !== type) return false;
      if (!q) return true;
      return (
        output.title.toLowerCase().includes(q) ||
        output.content.toLowerCase().includes(q) ||
        output.workflowRunId.toLowerCase().includes(q)
      );
    });
  }, [outputs, search, typeFilter]);

  const outputTypes = useMemo(
    () => [...new Set(outputs.map((output) => output.outputType))].sort(),
    [outputs],
  );

  return (
    <div className="flex flex-col gap-6 p-6">
      <PageHeader
        code="WORKFLOW OUTPUTS"
        title={workflow?.name ? `${workflow.name} — Outputs` : "Workflow outputs"}
        lede="Searchable output browser across workflow runs — reports and insights generated by execution."
      />

      <WorkflowSubNav workflowName={workflow?.name} active="outputs" />

      {error && <p className="text-sm text-[var(--color-danger)]">{error}</p>}

      <Panel title="Filters">
        <div className="flex flex-wrap gap-4">
          <TextField
            label="Search"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Title, content, run ID"
          />
          <TextField
            label="Output type"
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value)}
            placeholder={outputTypes[0] ?? "report"}
            {...(outputTypes.length > 0
              ? { hint: `Known: ${outputTypes.join(", ")}` }
              : {})}
          />
          <div className="flex items-end">
            <Button variant="secondary" onClick={() => void load()}>
              Refresh
            </Button>
          </div>
        </div>
      </Panel>

      <Panel title={`Outputs (${filtered.length})`}>
        {loading ? (
          <p className="text-sm text-[var(--color-text-tertiary)]">Loading…</p>
        ) : filtered.length === 0 ? (
          <p className="text-sm text-[var(--color-text-tertiary)]">
            No outputs match your filters. Execute the workflow to generate outputs.
          </p>
        ) : (
          <div className="flex flex-col gap-4">
            {filtered.map((output) => (
              <div
                key={output.outputId}
                className="rounded border border-[var(--color-border-default)] bg-[var(--color-surface-1)]"
              >
                <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--color-border-default)] px-4 py-3">
                  <div>
                    <p className="font-medium">{output.title}</p>
                    <p className="font-mono text-xs text-[var(--color-text-tertiary)]">
                      {output.workflowRunId} · {new Date(output.createdAt).toLocaleString()}
                    </p>
                  </div>
                  <div className="flex flex-wrap items-center gap-2">
                    <Badge>{output.outputType}</Badge>
                    <Button
                      variant="secondary"
                      onClick={() =>
                        setExpandedId((id) => (id === output.outputId ? null : output.outputId))
                      }
                    >
                      {expandedId === output.outputId ? "Hide" : "View"}
                    </Button>
                    <Link to={`/workflows/runs/${output.workflowRunId}/replay`}>
                      <Button variant="secondary">Replay</Button>
                    </Link>
                  </div>
                </div>
                {expandedId === output.outputId && (
                  <pre className="max-h-72 overflow-auto whitespace-pre-wrap p-4 text-xs text-[var(--color-text-secondary)]">
                    {output.content}
                  </pre>
                )}
              </div>
            ))}
          </div>
        )}
      </Panel>
    </div>
  );
}
